### ISSUE TITLE
Reorder Conditional/Complex transitions

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/module-builder#133]
It would be useful to be able to move conditional transitions up/down in order, as they execute in order, rather than having to change all the properties manually.

**Comment by arscan** [comment]
Addressed mostly in #176.  I say 'mostly', because a little more thought needs to be put into how we deal with 'else' conditions.  But my plan is to address that in #161 

This is ugly, but it works and we can refresh the UI in #178.

![screen shot 2018-05-22 at 9 35 04 am](https://user-images.githubusercontent.com/412901/40365801-76edd74c-5da3-11e8-8e39-4de798df595d.png)

**Comment by arscan** [comment]
Deployed.
