### ISSUE TITLE
Module remarks are formatted as long line with \n instead of multiple lines

### ISSUE THREAD

**Issue by dehall** [synthetichealth/module-builder#202]
Module-level remarks are saved as a single long line with line breaks from the editor included as \n. These should be broken up into multiple lines for readability. Note that this seems to already be the case for state-level remarks.

**Comment by jawalonoski** [comment]
I can't even seem to get module-level remarks to even function. State-level seem to work, depending on where I click out of the field. I can't seem to determine a reproducible set of steps.

**Comment by arscan** [comment]
Regarding losing changes:

If you edit something and click on the graph, the graph's handler don't let the event bubble up properly (I think), and this seems to cause the component we are using to handle the text fields to discard changes.

To replicate: make changes (to remarks, either state level or module level), and click anywhere other than the graph, and they should 'stick'.  Then make changes, and click on the graph, and they will go away.

The solutions I have in mind are fairly technical in nature.  But this bug is probably very annoying.

**Comment by arscan** [comment]
Updated and deployed.  I opened another issue to track the 'changes getting lost' problem.
